### ISSUE TITLE
fix deployment

### ISSUE THREAD

**Issue by dhimmel** [trangdata/zapad#1]
https://github.com/orgs/community/discussions/23885#discussioncomment-5404392

> GitHub Pages is available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server

we might have to make public, or get GH pro

**Comment by trangdata** [comment]
I’m cool with making this public.

**Comment by dhimmel** [comment]
Let's do that
