### ISSUE TITLE
cname does not take effect?

### ISSUE THREAD

**Issue by trangdata** [trangdata/zapad#2]
For some reason, new commit would update https://trangdata.github.io/zapad/ but the custom domain would disappear even though we set cname:

https://github.com/trangdata/zapad/blob/58c14353edf1d6920ac35c4ddb5115f11f88e3ba/.github/workflows/quarto.yml#L28

**Comment by dhimmel** [comment]
Is this still an issue? Was it related to the repo being private?

**Comment by trangdata** [comment]
Now resolved with b478e1aeff72bf9a86df4a4be183b0e5d4790fc5 and 054856e9d09ab46907a8600068f7969a50c81875.
